### ISSUE TITLE
How can I get a (NSData *)ipv4Address without a public getIPv4AddressFromHost method?

### ISSUE THREAD

**Issue by lexrus** [OliverLetterer/SPLPing#1]
Since you tagged this method as the designated initializer:

``` objective-c
- (instancetype)initWithHost:(NSString *)host ipv4Address:(NSData *)ipv4Address configuration:(SPLPingConfiguration *)configuration NS_DESIGNATED_INITIALIZER;
```

And I wanna retain a strong reference to a SPLPing instance(so that I won't use the class method). I can't figure out how to initialize an ipv4Address without getIPv4AddressFromHost. As I understood, ipv4Address can be resolved by the hostname.

Thanks.

**Comment by OliverLetterer** [comment]
You can always reimplement the private function getIPv4AddressFromHost in your own code base or retain the SPLPing instance after the completion handler of the class method fired.
